#Cloud_Config
hostname: #Give your VM a unique name, but use non-caps letters and numbers only. You can try otherwise, but it caused me issues.
rancher:
  console: ubuntu
  docker:
    engine: docker-18.09.2
  network:
    #Pfsense says that the Unbound resolver is tied to the router interface.  
    #This should be different on each interface, so I put in both.  This is probably unnecessary.
    dns:
      nameservers:
        - #Insert your resolver location here for testing purposes
        - 8.8.8.8
        - 1.1.1.1
    interfaces:
      #Add as many interfaces as needed.  You can also run this with dhcp set to "true", though I don't recommend it for the server,
      #but it MIGHT be okay for the agents.
      eth0:
        dhcp: false
        address: #Insert this computer's address here, in Classless inter-domain routing (CIDR) format, i.e. 192.168.1.5/24
        gateway: #Insert your gateway here.
        mtu: 1500

#I've been messing around with longhorn, which requires open-iscsi.  It also requires a change in open-iscsi's config, which I have not
#figured out how to streamline into a cloud-config.
write_files:
  - path: /etc/rc.local
    permissions: "0755"
    owner: root
    content: |
      #!/bin/bash
      wait-for-docker
      sudo apt update
      sudo apt install -y open-iscsi
ssh_authorized_keys:
  - #Insert your ssh-rsa keys here.
